FROM ubuntu:22.04
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    curl \
    unzip \
    bzip2 \
    libbz2-dev \
    zlib1g-dev \
    libncurses5-dev \
    libncursesw5-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
