FROM ubuntu:22.04

# Переменная окружения $SOFT
ENV SOFT=/soft

# Папка $SOFT
RUN mkdir -p $SOFT

RUN apt-get update && apt-get install -y \
    automake \
    make \
    gcc \
    perl \
    libcurl4-gnutls-dev \
    libssl-dev \
    libdeflate-dev \
    build-essential \
    wget \
    curl \
    unzip \
    bzip2 \
    libbz2-dev \
    zlib1g-dev \
    libncurses5-dev \
    libncursesw5-dev \
    liblzma-dev \
    cmake \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
    
# htslib 1.21
RUN cd /tmp && \
	wget https://github.com/samtools/htslib/releases/download/1.21/htslib-1.21.tar.bz2 && \
	tar -xjf htslib-1.21.tar.bz2 && \
	cd htslib-1.21 && \
	./configure --prefix=$SOFT/htslib-1.21 && \
        make -j$(nproc) && make install && \
	rm -rf /tmp/htslib-1.21*    

# Samtools 1.21
RUN cd /tmp && \
	wget https://github.com/samtools/samtools/releases/download/1.21/samtools-1.21.tar.bz2 && \
	tar -xjf samtools-1.21.tar.bz2 && \
	cd samtools-1.21 && \
	./configure --prefix=$SOFT/samtools-1.21 && \
	make -j$(nproc) && make install && \
	rm -rf /tmp/samtools-1.21*

# libdeflate 1.21
RUN cd /tmp && \
	wget https://github.com/ebiggers/libdeflate/releases/download/v1.21/libdeflate-1.21.tar.gz && \
	tar -xzf libdeflate-1.21.tar.gz && \
	cd libdeflate-1.21 && \
	cmake -B build && cmake --build build && \
	mkdir -p $SOFT/libdeflate-1.21/bin && \
	cp -r build/* $SOFT/libdeflate-1.21 && \
	cd / && \
	rm -rf /tmp/libdeflate-1.21*

# bcftools 1.21
RUN cd /tmp && \
	wget https://github.com/samtools/bcftools/releases/download/1.21/bcftools-1.21.tar.bz2 && \
	tar -xjf bcftools-1.21.tar.bz2 && \
	cd bcftools-1.21 && \
	./configure --prefix=$SOFT/bcftools-1.21 && \
	make -j$(nproc) && make install && \
	rm -rf /tmp/bcftools-1.21*

# vcftools 0.1.16
RUN cd /tmp && \
    wget https://github.com/vcftools/vcftools/releases/download/v0.1.16/vcftools-0.1.16.tar.gz && \
    tar -xzf vcftools-0.1.16.tar.gz && \
    cd vcftools-0.1.16 && \
    ./configure --prefix=$SOFT/vcftools-0.1.16 && \
    make -j$(nproc) && make install && \
    rm -rf /tmp/vcftools-0.1.16*

# Переменные
ENV SAMTOOLS=$SOFT/samtools-1.21/bin/samtools
ENV HTSLIB=$SOFT/htslib-1.21/bin/htslib
ENV LIBDEFLATE=$SOFT/libdeflate-1.21/libdeflate
ENV BCFTOOLS=$SOFT/bcftools-1.21/bcftools
ENV VCFTOOLS=$SOFT/vcftools-0.1.16/vcftools

# Пути библиотек в $PATH
ENV PATH=$SOFT/samtools-1.21/bin:$SOFT/htslib-1.21/bin:$SOFT/libdeflate-1.21/bin:$SOFT/bcftools-1.21/bin:$SOFT/vcftools-0.1.16/bin:$PATH
